spring:
  datasource:
    url: jdbc:h2:mem:testdb  # JDBC URL for H2 in-memory database
    driver-class-name: org.h2.Driver  # JDBC driver class for H2
    username: sa  # Default username for H2
    password:  # Default password for H2
  h2:
    console:
      enabled: true  # Enable H2 console for development
      path: /h2-console  # URL path for accessing H2 console
    tcpServer:
      enabled: true  # Enable H2 TCP server for remote access (optional)
      port: 9092  # TCP server port for H2 (optional)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Hibernate dialect for H2
    hibernate:
      ddl-auto: create-drop  # Automatically create and drop database schema
